CREATE TABLE utente (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipologia VARCHAR(128),
    nome VARCHAR(128),
    cognome VARCHAR(128),
    username VARCHAR(128),
    password VARCHAR(128),
    saldo_conto DECIMAL(20,2)
);

CREATE TABLE oggetto (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR(128),
    nome VARCHAR(128),
    url_immagine VARCHAR(128),
    descrizione VARCHAR(300),
    quantita INTEGER,
    prezzo DECIMAL(20,2),
    id_venditore INTEGER REFERENCES utente
);

INSERT INTO utente(id, tipologia, nome, cognome, username, password, saldo_conto)
VALUES (default, 'cliente', 'Alberto', 'Pranteddu', 'apranteddu', '1234', 200.80);

INSERT INTO utente(id, tipologia, nome, cognome, username, password, saldo_conto)
VALUES (default, 'venditore', 'Mario', 'Rossi', 'mrossi', '4321', 50.45);

INSERT INTO utente(id, tipologia, nome, cognome, username, password, saldo_conto)
VALUES (default, 'cliente', 'Giorgio', 'Zedda', 'gzedda', '0101', 30.33);

INSERT INTO utente(id, tipologia, nome, cognome, username, password, saldo_conto)
VALUES (default, 'venditore', 'Carlo', 'Anedda', 'canedda', '1010', 45.74);





INSERT INTO oggetto(id, categoria, nome, url_immagine, descrizione, quantita, prezzo, id_venditore)
VALUES (default, 'completo', 'Hudora Skateboard, ABEC 5', 'img/hudora_skate.jpg',
        'Skate completo ed economico adatto ai principianti', 5, 25.46, 2);

INSERT INTO oggetto(id, categoria, nome, url_immagine, descrizione, quantita, prezzo, id_venditore)
VALUES (default, 'trucks', 'Truck Independent: 149 Salazar Doomsayers Matte Nero Std Stage 11',
        'img/truck_independent.jpg', 'Trucks independent di alta qualita', 3, 40.71, 2);

INSERT INTO oggetto(id, categoria, nome, url_immagine, descrizione, quantita, prezzo, id_venditore)
VALUES (default, 'tavola', 'Tavola Element: Westgate Split 8', 'img/tavola_element.jpg', 
        'Tavola a 7 stratti di acero canadese', 2, 58.70, 2);

INSERT INTO oggetto(id, categoria, nome, url_immagine, descrizione, quantita, prezzo, id_venditore)
VALUES (default, 'tavola', 'Tavola Zero: Dead Presidents Jamie Thomas 8.375', 'img/tavola_zero.jpg', 
        'Tavola a 7 stratti di acero canadese', 1, 63.82, 2);

INSERT INTO oggetto(id, categoria, nome, url_immagine, descrizione, quantita, prezzo, id_venditore)
VALUES (default, 'ruote', 'Spitfire - Kit di 4 ruote per skateboard Bighead', 'img/ruote_spitfire.jpg', 
        'Le ruote spitfire sono tra le migliori in circolazione, adatte a qualsiasi terreno.', 7, 46.57, 2);

INSERT INTO oggetto(id, categoria, nome, url_immagine, descrizione, quantita, prezzo, id_venditore)
VALUES (default, 'cuscinetti', 'Cuscinetti Skateboard Enuff Black', 'img/cuscinetti_enuff_black.jpg', 
        'Set di cuscinetti enuff black', 4, 14.99, 2);



